#!/bin/bash
# exec $(dirname $0)/${STEP:-stepA_mal} "${@}"
echo running ${STEP:-stepA_mal} "${@}"
cd $(dirname $0) && cargo r --bin step5_tco "${@}" #2>/dev/null
# cd $(dirname $0) && cargo r --bin ${STEP:-stepA_mal} "${@}" 2>/dev/null
